import axios from 'axios';
import { NextRequest, NextResponse } from 'next/server';

type Player = {
  PlayerID: number;
  SportsDataID: string;
  Status: string;
  TeamID: number;
  Team: string;
  Jersey: number | null;
  PositionCategory: string;
  Position: string;
  FirstName: string;
  LastName: string;
  BirthDate: string; // ISO 8601形式の日付（例: "1986-03-25T00:00:00"）
  BirthCity: string;
  BirthState: string | null;
  BirthCountry: string;
  GlobalTeamID: number;
  Height: number; // 単位はインチ
  Weight: number; // 単位はポンド
};

export type GetPlayersProfileByTeamName = Player[];

export async function GET(req: NextRequest, { params }: { params: { teamName: string } }) {
  const { teamName } = params;
  const url = `https://api.sportsdata.io/v3/nba/scores/json/PlayersBasic/${teamName}?key=${process.env.NBA_API_KEY}`;

  try {
    // const result = await axios.get(url);
    return NextResponse.json(mockData);
  } catch (error) {
    // return NextResponse.json({ error: error, status: 500 });
    return NextResponse.json([]);
  }
}

const mockData = [
  {
    PlayerID: 20000482,
    SportsDataID: '',
    Status: 'Active',
    TeamID: 26,
    Team: 'GS',
    Jersey: 23,
    PositionCategory: 'F',
    Position: 'PF',
    FirstName: 'Draymond',
    LastName: 'Green',
    BirthDate: '1990-03-04T00:00:00',
    BirthCity: 'Saginaw',
    BirthState: 'MI',
    BirthCountry: 'USA',
    GlobalTeamID: 20000026,
    Height: 78,
    Weight: 235,
  },
  {
    PlayerID: 20000485,
    SportsDataID: '',
    Status: 'Active',
    TeamID: 26,
    Team: 'GS',
    Jersey: 30,
    PositionCategory: 'G',
    Position: 'PG',
    FirstName: 'Stephen',
    LastName: 'Curry',
    BirthDate: '1988-03-14T00:00:00',
    BirthCity: 'Akron',
    BirthState: 'OH',
    BirthCountry: 'USA',
    GlobalTeamID: 20000026,
    Height: 75,
    Weight: 200,
  },
  {
    PlayerID: 20000659,
    SportsDataID: '',
    Status: 'Active',
    TeamID: 26,
    Team: 'GS',
    Jersey: 1,
    PositionCategory: 'F',
    Position: 'SF',
    FirstName: 'Kyle',
    LastName: 'Anderson',
    BirthDate: '1993-09-20T00:00:00',
    BirthCity: 'New York',
    BirthState: 'NY',
    BirthCountry: 'USA',
    GlobalTeamID: 20000026,
    Height: 81,
    Weight: 245,
  },
  {
    PlayerID: 20000795,
    SportsDataID: '',
    Status: 'Active',
    TeamID: 26,
    Team: 'GS',
    Jersey: 22,
    PositionCategory: 'F',
    Position: 'SF',
    FirstName: 'Andrew',
    LastName: 'Wiggins',
    BirthDate: '1995-02-23T00:00:00',
    BirthCity: 'Toronto',
    BirthState: 'ON',
    BirthCountry: 'Canada',
    GlobalTeamID: 20000026,
    Height: 79,
    Weight: 209,
  },
  {
    PlayerID: 20001455,
    SportsDataID: '',
    Status: 'Active',
    TeamID: 26,
    Team: 'GS',
    Jersey: 5,
    PositionCategory: 'C',
    Position: 'C',
    FirstName: 'Kevon',
    LastName: 'Looney',
    BirthDate: '1996-02-06T00:00:00',
    BirthCity: 'Milwaukee',
    BirthState: 'WI',
    BirthCountry: 'USA',
    GlobalTeamID: 20000026,
    Height: 81,
    Weight: 257,
  },
  {
    PlayerID: 20001673,
    SportsDataID: '',
    Status: 'Active',
    TeamID: 26,
    Team: 'GS',
    Jersey: 7,
    PositionCategory: 'F',
    Position: 'SF',
    FirstName: 'Buddy',
    LastName: 'Hield',
    BirthDate: '1992-12-17T00:00:00',
    BirthCity: 'Freeport',
    BirthState: null,
    BirthCountry: 'Bahamas',
    GlobalTeamID: 20000026,
    Height: 76,
    Weight: 220,
  },
  {
    PlayerID: 20001730,
    SportsDataID: '',
    Status: 'Active',
    TeamID: 26,
    Team: 'GS',
    Jersey: 0,
    PositionCategory: 'G',
    Position: 'PG',
    FirstName: 'Gary',
    LastName: 'Payton II',
    BirthDate: '1992-12-01T00:00:00',
    BirthCity: 'Seattle',
    BirthState: 'WA',
    BirthCountry: 'USA',
    GlobalTeamID: 20000026,
    Height: 75,
    Weight: 195,
  },
  {
    PlayerID: 20001994,
    SportsDataID: '',
    Status: 'Active',
    TeamID: 26,
    Team: 'GS',
    Jersey: 31,
    PositionCategory: 'F',
    Position: 'SF',
    FirstName: 'Kevin',
    LastName: 'Knox II',
    BirthDate: '1999-08-11T00:00:00',
    BirthCity: 'Phoenix',
    BirthState: 'AZ',
    BirthCountry: 'USA',
    GlobalTeamID: 20000026,
    Height: 79,
    Weight: 215,
  },
  {
    PlayerID: 20002029,
    SportsDataID: '',
    Status: 'Active',
    TeamID: 26,
    Team: 'GS',
    Jersey: 8,
    PositionCategory: 'G',
    Position: 'SG',
    FirstName: "De'Anthony",
    LastName: 'Melton',
    BirthDate: '1998-05-28T00:00:00',
    BirthCity: 'North Hollywood',
    BirthState: 'CA',
    BirthCountry: 'USA',
    GlobalTeamID: 20000026,
    Height: 75,
    Weight: 200,
  },
  {
    PlayerID: 20002655,
    SportsDataID: '',
    Status: 'Active',
    TeamID: 26,
    Team: 'GS',
    Jersey: 4,
    PositionCategory: 'G',
    Position: 'SG',
    FirstName: 'Moses',
    LastName: 'Moody',
    BirthDate: '2002-05-31T00:00:00',
    BirthCity: 'Little Rock',
    BirthState: 'AR',
    BirthCountry: 'USA',
    GlobalTeamID: 20000026,
    Height: 77,
    Weight: 215,
  },
  {
    PlayerID: 20002661,
    SportsDataID: '',
    Status: 'Active',
    TeamID: 26,
    Team: 'GS',
    Jersey: 0,
    PositionCategory: 'F',
    Position: 'PF',
    FirstName: 'Jonathan',
    LastName: 'Kuminga',
    BirthDate: '2002-10-06T00:00:00',
    BirthCity: 'Goma',
    BirthState: null,
    BirthCountry: 'DR Congo',
    GlobalTeamID: 20000026,
    Height: 79,
    Weight: 225,
  },
  {
    PlayerID: 20002859,
    SportsDataID: '',
    Status: 'Active',
    TeamID: 26,
    Team: 'GS',
    Jersey: 43,
    PositionCategory: 'G',
    Position: 'SG',
    FirstName: 'Lindy',
    LastName: 'Waters III',
    BirthDate: '1997-07-28T00:00:00',
    BirthCity: 'Norman',
    BirthState: 'OK',
    BirthCountry: 'USA',
    GlobalTeamID: 20000026,
    Height: 78,
    Weight: 198,
  },
  {
    PlayerID: 20002933,
    SportsDataID: '',
    Status: 'Active',
    TeamID: 26,
    Team: 'GS',
    Jersey: 15,
    PositionCategory: 'F',
    Position: 'SF',
    FirstName: 'Gui',
    LastName: 'Santos',
    BirthDate: '2002-06-22T00:00:00',
    BirthCity: 'Brasilia',
    BirthState: null,
    BirthCountry: 'Brazil',
    GlobalTeamID: 20000026,
    Height: 79,
    Weight: 218,
  },
  {
    PlayerID: 20003012,
    SportsDataID: '',
    Status: 'Active',
    TeamID: 26,
    Team: 'GS',
    Jersey: 61,
    PositionCategory: 'G',
    Position: 'SG',
    FirstName: 'Pat',
    LastName: 'Spencer',
    BirthDate: '1996-07-04T00:00:00',
    BirthCity: 'Davidson',
    BirthState: 'MD',
    BirthCountry: 'USA',
    GlobalTeamID: 20000026,
    Height: 75,
    Weight: 205,
  },
  {
    PlayerID: 20003065,
    SportsDataID: '',
    Status: 'Active',
    TeamID: 26,
    Team: 'GS',
    Jersey: 32,
    PositionCategory: 'F',
    Position: 'PF',
    FirstName: 'Trayce',
    LastName: 'Jackson-Davis',
    BirthDate: '2000-02-22T00:00:00',
    BirthCity: 'Greenwood',
    BirthState: 'IN',
    BirthCountry: 'USA',
    GlobalTeamID: 20000026,
    Height: 80,
    Weight: 245,
  },
  {
    PlayerID: 20003068,
    SportsDataID: '',
    Status: 'Active',
    TeamID: 26,
    Team: 'GS',
    Jersey: 2,
    PositionCategory: 'G',
    Position: 'SG',
    FirstName: 'Brandin',
    LastName: 'Podziemski',
    BirthDate: '2003-02-25T00:00:00',
    BirthCity: 'Greenfield',
    BirthState: 'WI',
    BirthCountry: 'USA',
    GlobalTeamID: 20000026,
    Height: 76,
    Weight: 203,
  },
  {
    PlayerID: 20003253,
    SportsDataID: '',
    Status: 'Active',
    TeamID: 26,
    Team: 'GS',
    Jersey: 21,
    PositionCategory: 'C',
    Position: 'C',
    FirstName: 'Quinten',
    LastName: 'Post',
    BirthDate: '2000-03-21T00:00:00',
    BirthCity: 'Amsterdam',
    BirthState: null,
    BirthCountry: 'Netherlands',
    GlobalTeamID: 20000026,
    Height: 84,
    Weight: 244,
  },
  {
    PlayerID: 20003264,
    SportsDataID: '',
    Status: 'Active',
    TeamID: 26,
    Team: 'GS',
    Jersey: 3,
    PositionCategory: 'G',
    Position: 'PG',
    FirstName: 'Reece',
    LastName: 'Beekman',
    BirthDate: '2001-10-08T00:00:00',
    BirthCity: 'Milwaukee',
    BirthState: 'WI',
    BirthCountry: 'USA',
    GlobalTeamID: 20000026,
    Height: 73,
    Weight: 196,
  },
  {
    PlayerID: 20003265,
    SportsDataID: '',
    Status: 'Active',
    TeamID: 26,
    Team: 'GS',
    Jersey: 26,
    PositionCategory: 'F',
    Position: 'SF',
    FirstName: 'Blake',
    LastName: 'Hinson',
    BirthDate: '1999-12-26T00:00:00',
    BirthCity: 'Deltona',
    BirthState: 'Florida',
    BirthCountry: 'USA',
    GlobalTeamID: 20000026,
    Height: 79,
    Weight: 235,
  },
  {
    PlayerID: 20003308,
    SportsDataID: '',
    Status: 'Active',
    TeamID: 26,
    Team: 'GS',
    Jersey: 44,
    PositionCategory: 'F',
    Position: 'PF',
    FirstName: 'Jackson',
    LastName: 'Rowe',
    BirthDate: '1997-01-04T00:00:00',
    BirthCity: 'Toronto',
    BirthState: 'ON',
    BirthCountry: 'Canada',
    GlobalTeamID: 20000026,
    Height: 79,
    Weight: 210,
  },
];
