version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      timezone: Asia/Tokyo
      time: 09:00
    target-branch: develop
    pull-request-branch-name:
      pattern: dependabot/{{dependency-name}}@{{version}}
    commit-message:
      prefix: chore(deps): update {{dependency-name}} to {{new-version}}
      prefix-development: chore(deps-dev): update {{dependency-name}} to {{new-version}}