version: 2
updates:
  - package-ecosystem: "npm"
    directory: /
    schedule:
      interval: daily
      timezone: Asia/Tokyo
      time: "09:00"
    target-branch: develop
    pull-request-branch-name:
      separator: "-"
    commit-message:
      prefix: "chore(deps): update"
      prefix-development: "chore(deps-dev): update"
