import './globals.css';
import type { Metadata } from 'next';

import SideBarLink from '@/components/molecules/SideBarLink/SideBarLink';
import Header from '@/components/organisms/Header/Header';
import Head from 'next/head';

import { Roboto_Condensed, Zen_Kaku_Gothic_Antique } from 'next/font/google';
import Footer from '@/components/organisms/Footer/Footer';

const robotoCondensedFont = Roboto_Condensed({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-RobotoCondensed',
});

const zenKakuGothicFont = Zen_Kaku_Gothic_Antique({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-ZenKakuGothic',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <title>NBA PORTAL</title>
      </Head>

      <body
        className={` bg-[#E0E0E0] ${robotoCondensedFont.className} ${zenKakuGothicFont.className} font-roboto antialiased`}
      >
        {/* ヘッダー */}
        <Header />

        {/* サイドバー */}
        <div className=" flex flex-row ">
          <div className="flex flex-col gap-3 border-r pr-10 p-3 ">
            <SideBarLink href="/">HOME</SideBarLink>
            <SideBarLink href="/teams">TEAMS</SideBarLink>
            <SideBarLink href="/players/active">PLAYERS</SideBarLink>
            <SideBarLink href="/news">NEWS</SideBarLink>
          </div>
          <div className="p-7">{children}</div>
        </div>

        {/* フッター */}
        <Footer />
      </body>
    </html>
  );
}
