export const newsMockData = [
  {
    NewsID: 98628,
    Source: 'RotoBaller',
    Updated: '2024-10-03T12:33:24',
    TimeAgo: '19 hours ago',
    Title: 'Julius Randle Confirmed As Starter On New Team',
    Content:
      "Minnesota Timberwolves power forward Julius Randle (shoulder) will remain a starter on his new team. Randle hasn't come off the bench since the 2018-19 campaign, and Timberwolves head coach Chris Finch has now confirmed that the veteran will continue to start in Minnesota. Randle has been an All-Star in back-to-back campaigns, so it would have been quite a shock if he had landed on the bench with the Timberwolves, although Naz Reid offers a good alternative to Finch. Assuming he stays healthy, fantasy managers should get another productive campaign out of Randle. He averaged 24.0 points, 9.5 rebounds, and 5.0 assists last season.",
    Url: 'https://www.rotoballer.com/player-news/julius-randle-confirmed-as-starter-on-new-team/1460113',
    TermsOfUse:
      "RotoBaller Premium News feeds are provided for commercial use and in accordance to the terms set forth within your SportsDataIO's commercial agreement. Please contact sales@sportsdata.io with any questions.",
    Author: 'Staff',
    Categories: 'Lineup',
    PlayerID: 20000710,
    TeamID: 16,
    Team: 'MIN',
    PlayerID2: null,
    TeamID2: null,
    Team2: null,
    OriginalSource: 'Evan Sidery',
    OriginalSourceUrl: 'https://x.com/esidery/status/1841628009528168774',
  },
  {
    NewsID: 98616,
    Source: 'RotoBaller',
    Updated: '2024-10-02T10:56:16',
    TimeAgo: 'yesterday',
    Title: 'Keon Ellis Begins Training Camp As Starter',
    Content:
      'Sacramento Kings shooting guard Keon Ellis is working with the starting group to begin training camp. Kings head coach Mike Brown sees Ellis as a starter "for now." Sacramento has a spot open in the first unit due to Kevin Huerter\'s (shoulder) absence. Ellis\' fantasy value will get a big boost if he sticks with the starters. The 24-year-old started 21 games last season, averaging 8.8 points, 3.5 rebounds, 2.3 assists, and 1.7 steals. Ellis is mainly known as a defensive specialist, but he can contribute across the board if given enough playing time.',
    Url: 'https://www.rotoballer.com/player-news/keon-ellis-begins-training-camp-as-starter/1459265',
    TermsOfUse:
      "RotoBaller Premium News feeds are provided for commercial use and in accordance to the terms set forth within your SportsDataIO's commercial agreement. Please contact sales@sportsdata.io with any questions.",
    Author: 'Staff',
    Categories: 'Lineup',
    PlayerID: 20002905,
    TeamID: 30,
    Team: 'SAC',
    PlayerID2: null,
    TeamID2: null,
    Team2: null,
    OriginalSource: 'James Ham',
    OriginalSourceUrl: 'https://x.com/james_hamnba/status/1841215564494057508',
  },
  {
    NewsID: 98595,
    Source: 'RotoBaller',
    Updated: '2024-10-01T00:51:56',
    TimeAgo: '3 days ago',
    Title: 'Dyson Daniels Sets Big Defensive Goals',
    Content:
      'Atlanta Hawks guard Dyson Daniels is honing in on defense this season, with a bold goal in mind. "I have a big goal of trying to make the first-team All-Defense," Daniels stated during Hawks Media Day on Monday. Atlanta, which ranked 27th in defense last season, will welcome his focus. While the young guard has shown defensive potential, fantasy managers will hope he can boost his offensive production. He averaged 5.8 points in 22.3 minutes per game. His shooting struggles, including 31.1% from three-point range and 64.2% from the free-throw line, indicate that improving his offensive efficiency is essential for his development. At just 21 years of age, Daniels has time to refine his game and could be a sneaky draft pick with upside.',
    Url: 'https://www.rotoballer.com/player-news/dyson-daniels-sets-big-defensive-goals/1458219',
    TermsOfUse:
      "RotoBaller Premium News feeds are provided for commercial use and in accordance to the terms set forth within your SportsDataIO's commercial agreement. Please contact sales@sportsdata.io with any questions.",
    Author: 'Staff',
    Categories: 'Top-Headlines',
    PlayerID: 20002878,
    TeamID: 3,
    Team: 'ATL',
    PlayerID2: null,
    TeamID2: null,
    Team2: null,
    OriginalSource: 'Kevin Chouinard',
    OriginalSourceUrl:
      'https://x.com/klchouinard/status/1840799139174478027?s=46&amp;t=Xc76jFDCoPKFYC3OdNRagw',
  },
  {
    NewsID: 98588,
    Source: 'RotoBaller',
    Updated: '2024-09-30T15:54:05',
    TimeAgo: '3 days ago',
    Title: 'Khris Middleton Still Not Cleared For Five-On-Five Work',
    Content:
      "Milwaukee Bucks guard/forward Khris Middleton (ankle) underwent procedures on both ankles during the offseason and he has yet to be cleared to partake in five-on-five action, according to Chris Haynes. Middleton is progressing and is expected to be included in most camp activities, but he wouldn't be cleared to play an actual preseason game just yet. The 33-year-old appeared in 88 regular-season games over the last two seasons as he's dealt with a series of different injuries. Last year, he averaged 15.1 points, 4.7 rebounds, and 5.3 assists across 27.0 minutes per game. If healthy, Middleton is one of the better wings in the Eastern Conference, but as he's getting older, his health has been the biggest question mark.",
    Url: 'https://www.rotoballer.com/player-news/khris-middleton-still-not-cleared-for-five-on-five-work/1457805',
    TermsOfUse:
      "RotoBaller Premium News feeds are provided for commercial use and in accordance to the terms set forth within your SportsDataIO's commercial agreement. Please contact sales@sportsdata.io with any questions.",
    Author: 'Staff',
    Categories: 'Injuries, Top-Headlines',
    PlayerID: 20000500,
    TeamID: 15,
    Team: 'MIL',
    PlayerID2: null,
    TeamID2: null,
    Team2: null,
    OriginalSource: 'Chris Haynes',
    OriginalSourceUrl: 'https://x.com/ChrisBHaynes/status/1840151476808945892',
  },
  {
    NewsID: 98586,
    Source: 'RotoBaller',
    Updated: '2024-09-29T02:57:29',
    TimeAgo: '5 days ago',
    Title: 'Jose Alvarado, Pelicans Agree To A Two-Year Extension',
    Content:
      "According to NBA insider Shams Charania, New Orleans Pelicans guard Jose Alvarado agreed to a two-year, $9 million extension with the team. The 26-year-old has spent his entire career in New Orleans, averaging 7.5 points, 2.7 assists, and 1.2 steals. Unfortunately, he has struggled to stay healthy, logging 61 games or fewer in each season since entering the National Basketball Association. Alvarado will hold a consistent spot in the rotation behind Dejounte Murray and CJ McCollum this season. However, he won't be a routine fantasy provider, although his defensive prowess gives him added value in category formats.",
    Url: 'https://www.rotoballer.com/player-news/jose-alvarado-pelicans-agree-to-a-two-year-extension/1456600',
    TermsOfUse:
      "RotoBaller Premium News feeds are provided for commercial use and in accordance to the terms set forth within your SportsDataIO's commercial agreement. Please contact sales@sportsdata.io with any questions.",
    Author: 'Staff',
    Categories: 'Injuries, Top-Headlines',
    PlayerID: 20002732,
    TeamID: 23,
    Team: 'NO',
    PlayerID2: null,
    TeamID2: null,
    Team2: null,
    OriginalSource: 'Shams Charania',
    OriginalSourceUrl: 'https://x.com/ShamsCharania/status/1840121203547353232',
  },
  {
    NewsID: 98581,
    Source: 'RotoBaller',
    Updated: '2024-09-28T02:55:05',
    TimeAgo: '6 days ago',
    Title: 'Devin Vassell Out Until At Least November',
    Content:
      "San Antonio Spurs guard Devin Vassell (foot) is anticipated to miss the start of the season. The 2020 No. 11 overall pick averaged a career-high 19.5 points last season. Unfortunately, he suffered a stress fracture in his right foot and was sidelined near the end of the 2023-24 campaign. An update on Vassell's status isn't expected until November 1, although it's unknown when he'll be back on the floor. Without question, the latest update won't earn him attention from fantasy managers heading into the year, especially since he remains without a firm return date. To make matters worse, it should take him time to ramp up to his usual workload once cleared. But until Vassell is back, Malaki Branham, averaging 11.6 points, 2.8 rebounds, and 2.5 assists in 29 starts last season, will likely take his place in the rotation.",
    Url: 'https://www.rotoballer.com/player-news/devin-vassell-out-until-at-least-november/1455824',
    TermsOfUse:
      "RotoBaller Premium News feeds are provided for commercial use and in accordance to the terms set forth within your SportsDataIO's commercial agreement. Please contact sales@sportsdata.io with any questions.",
    Author: 'Staff',
    Categories: 'Injuries, Top-Headlines',
    PlayerID: 20002536,
    TeamID: 24,
    Team: 'SA',
    PlayerID2: null,
    TeamID2: null,
    Team2: null,
    OriginalSource: 'Tim Bontemps',
    OriginalSourceUrl:
      'https://www.espn.com/nba/story/_/id/41477809/spurs-devin-vassell-start-regular-season',
  },
  {
    NewsID: 98576,
    Source: 'RotoBaller',
    Updated: '2024-09-25T12:10:04',
    TimeAgo: '8 days ago',
    Title: 'Jayson Tatum Works On His Shooting During Offseason',
    Content:
      'Boston Celtics forward Jayson Tatum spent some of the offseason working on his shooting, telling the media on Tuesday that he has worked through "a few mechanical things" on his jumper with trainer Drew Hanlen. Tatum has developed into one of the best scorers in the league, but his numbers dipped in 2023-24. The five-time All-Star went from averaging 30 points a night to getting 26.9 points. Tatum shot a career-low 28.3 percent from three-point range in the 2024 playoffs and couldn\'t get anything to fall from deep at the Paris Olympics. The Celtics star enters the new season after signing the biggest extension in NBA history and is expected to be out to prove his worth after being largely overlooked by Team USA in the summer.',
    Url: 'https://www.rotoballer.com/player-news/jayson-tatum-worked-on-his-shooting-during-offseason/1453250',
    TermsOfUse:
      "RotoBaller Premium News feeds are provided for commercial use and in accordance to the terms set forth within your SportsDataIO's commercial agreement. Please contact sales@sportsdata.io with any questions.",
    Author: 'Staff',
    Categories: 'Lineup',
    PlayerID: 20001829,
    TeamID: 9,
    Team: 'BOS',
    PlayerID2: null,
    TeamID2: null,
    Team2: null,
    OriginalSource: 'Jay King',
    OriginalSourceUrl: 'https://x.com/ByJayKing/status/1838600200694255693',
  },
  {
    NewsID: 98562,
    Source: 'RotoBaller',
    Updated: '2024-09-24T01:31:52',
    TimeAgo: '10 days ago',
    Title: 'Derrick Rose Waived By Memphis',
    Content:
      "The Grizzlies waived guard Derrick Rose on Monday. The 35-year-old appeared in 24 regular season contests for Memphis last season, averaging 8.0 points, 3.3 assists, and 1.9 rebounds. With one year left on his former deal, he requested his release, indicating his intention to remain playing. Without question, Rose's best days are well behind him. However, he was semi-productive in his seven starts with the Grizzlies in 2023-24, so he could have value at times during the 2024-25 campaign.",
    Url: 'https://www.rotoballer.com/player-news/derrick-rose-waived-by-memphis/1452319',
    TermsOfUse:
      "RotoBaller Premium News feeds are provided for commercial use and in accordance to the terms set forth within your SportsDataIO's commercial agreement. Please contact sales@sportsdata.io with any questions.",
    Author: 'Staff',
    Categories: 'Lineup, Transactions',
    PlayerID: 20000516,
    TeamID: null,
    Team: null,
    PlayerID2: null,
    TeamID2: null,
    Team2: null,
    OriginalSource: 'NBA.com',
    OriginalSourceUrl: 'https://www.nba.com/players/transactions',
  },
  {
    NewsID: 98558,
    Source: 'RotoBaller',
    Updated: '2024-09-23T18:45:08',
    TimeAgo: '10 days ago',
    Title: 'Harry Giles III Heading To Charlotte',
    Content:
      "Free-agent center/forward Harry Giles III agreed to a training camp deal with the Charlotte Hornets on Sunday. According to Shams Charania of The Athletic, he'll compete for a roster spot on a very bare-bones roster that suffered a lot of injuries last season. Giles didn't play at all in the NBA during the 2021-22 and 2022-23 seasons, then came back to play for the Brooklyn Nets and Los Angeles Lakers last year. Through 23 total appearances last season, Giles averaged 2.4 points and 1.3 rebounds across 4.3 minutes per game. Knee injuries have been his biggest issue since being drafted 20th overall in 2017, but he may find a depth spot if he can stay healthy and compete through the preseason.",
    Url: 'https://www.rotoballer.com/player-news/harry-giles-iii-heading-to-charlotte/1452085',
    TermsOfUse:
      "RotoBaller Premium News feeds are provided for commercial use and in accordance to the terms set forth within your SportsDataIO's commercial agreement. Please contact sales@sportsdata.io with any questions.",
    Author: 'Staff',
    Categories: 'Transactions',
    PlayerID: 20001827,
    TeamID: 2,
    Team: 'CHA',
    PlayerID2: null,
    TeamID2: null,
    Team2: null,
    OriginalSource: 'Shams Charania',
    OriginalSourceUrl: 'https://x.com/ShamsCharania/status/1837896225128907099',
  },
  {
    NewsID: 98556,
    Source: 'RotoBaller',
    Updated: '2024-09-22T01:41:39',
    TimeAgo: '12 days ago',
    Title: 'Julius Randle "Recovering Well"',
    Content:
      "New York Knicks forward Julius Randle expects \"to be ready to play by or near the start of the season.\" The multi-time All-Star injured his ankle in January. He initially opted for rehab instead of surgery, hoping to join the Knicks for the postseason. Unfortunately, rehab wasn't successful, resulting in Randle going under the knife in April. From a production standpoint, the 24-year-old had one of the best seasons of his career in 2023-24, averaging 24.0 points, 9.2 rebounds, and 5.0 assists in 46 games. Without question, he is one of the most underrated players in the National Basketball Association. However, the Knicks' roster looks drastically different from when Randle was on the floor last, so it's hard to predict how the new additions might impact his fantasy contributions. Still, as long as he stays healthy, he should remain a reliable fantasy asset.",
    Url: 'https://www.rotoballer.com/player-news/julius-randle-recovering-well/1450768',
    TermsOfUse:
      "RotoBaller Premium News feeds are provided for commercial use and in accordance to the terms set forth within your SportsDataIO's commercial agreement. Please contact sales@sportsdata.io with any questions.",
    Author: 'Staff',
    Categories: 'Injuries, Top-Headlines',
    PlayerID: 20000710,
    TeamID: 6,
    Team: 'NY',
    PlayerID2: null,
    TeamID2: null,
    Team2: null,
    OriginalSource: 'Chris Herring',
    OriginalSourceUrl:
      'https://www.espn.com/nba/story/_/id/41329326/jimmy-butler-kristaps-porzingis-key-players-injury-returns-2024-25-nba-season',
  },
  {
    NewsID: 98550,
    Source: 'RotoBaller',
    Updated: '2024-09-20T15:52:01',
    TimeAgo: '13 days ago',
    Title: '76ers, Joel Embiid Agree On Three-Year Extension',
    Content:
      "Philadelphia 76ers center Joel Embiid has officially agreed on a three-year extension that will keep him in Philadelphia through 2027-28 with a player's option for 2028-29. According to Adam Schefter, the three-year max extension is worth $192.9 million and it gives the 2023 MVP a total of $299.5 million in guaranteed money through the 2028-29 season. Since stepping on the floor for the Sixers in 2016, Embiid has been the key piece on both sides of the ball. Now that Daryl Morey and company have put a championship-or-bust roster around him, it's time for him to lead them to the promised land. As long as he's healthy, he should also remain one of the best fantasy basketball assets in the league. Last season, the big man averaged 34.7 points, 11.0 rebounds, 5.6 assists, 1.2 steals, and 1.7 blocks per game across 39 appearances.",
    Url: 'https://www.rotoballer.com/player-news/76ers-joel-embiid-agree-on-three-year-extension/1449257',
    TermsOfUse:
      "RotoBaller Premium News feeds are provided for commercial use and in accordance to the terms set forth within your SportsDataIO's commercial agreement. Please contact sales@sportsdata.io with any questions.",
    Author: 'Staff',
    Categories: 'Top-Headlines, Transactions',
    PlayerID: 20000726,
    TeamID: 7,
    Team: 'PHI',
    PlayerID2: null,
    TeamID2: null,
    Team2: null,
    OriginalSource: 'Adam Schefter',
    OriginalSourceUrl:
      'https://x.com/adamschefter/status/1837121463599366320?s=46&amp;t=JRlxs6xfOfXiLVBmvO2FbA',
  },
  {
    NewsID: 98547,
    Source: 'RotoBaller',
    Updated: '2024-09-18T01:18:02',
    TimeAgo: '16 days ago',
    Title: 'Klay Thompson Ready For A New Chapter In Dallas',
    Content:
      'Dallas Mavericks guard/forward Klay Thompson is ready to start another chapter after spending his entire career in Golden State. "I\'m excited for a whole new chapter of my career that has a chance to be so special," said Thompson to The Dallas Morning News. "I know we can do something special." Thompson\'s resume includes four NBA championships and five All-Star selections. Unfortunately, he is coming off a down year, averaging 17.9 points and 38.7% shooting from behind the arc. The 34-year-old also spent time coming off the bench, which caused friction with his previous coach, Steve Kerr. But Thompson should remain in the starting lineup all year, so he could have a bounce-back year as long as he stays healthy.',
    Url: 'https://www.rotoballer.com/player-news/klay-thompson-ready-for-a-new-chapter-in-dallas/1447202',
    TermsOfUse:
      "RotoBaller Premium News feeds are provided for commercial use and in accordance to the terms set forth within your SportsDataIO's commercial agreement. Please contact sales@sportsdata.io with any questions.",
    Author: 'Staff',
    Categories: 'Lineup, Risers, Top-Headlines',
    PlayerID: 20000486,
    TeamID: 25,
    Team: 'DAL',
    PlayerID2: null,
    TeamID2: null,
    Team2: null,
    OriginalSource: 'Jose Sanchez Cordova',
    OriginalSourceUrl:
      'https://www.dallasnews.com/sports/mavericks/2024/09/14/new-and-old-dallas-mavericks-alike-hit-the-hardcourt-for-dirk-nowitzkis-tennis-classic/',
  },
  {
    NewsID: 98540,
    Source: 'RotoBaller',
    Updated: '2024-09-17T13:25:03',
    TimeAgo: '16 days ago',
    Title: 'Marcus Morris Sr. Joins Knicks For Training Camp',
    Content:
      "Veteran forward Marcus Morris Sr. has signed an Exhibit 9 contract with the New York Knicks. The 35-year-old will try to battle out a roster spot in training camp to extend his NBA career into a 14th year. Morris Sr. split last season between Philadelphia and Cleveland, averaging 6.4 points in 16.7 minutes. The Philadelphia native has remained a savvy scorer despite being on the wrong side of 30. However, if he makes the team, Morris Sr. will only be seen as a depth piece in New York and won't get enough action in normal circumstances to make an impact in fantasy basketball.",
    Url: 'https://www.rotoballer.com/player-news/marcus-morris-sr-joins-knicks-for-training-camp/1446705',
    TermsOfUse:
      "RotoBaller Premium News feeds are provided for commercial use and in accordance to the terms set forth within your SportsDataIO's commercial agreement. Please contact sales@sportsdata.io with any questions.",
    Author: 'Staff',
    Categories: 'Lineup',
    PlayerID: 20000847,
    TeamID: 6,
    Team: 'NY',
    PlayerID2: null,
    TeamID2: null,
    Team2: null,
    OriginalSource: 'Mollie Walker',
    OriginalSourceUrl:
      'https://nypost.com/2024/09/15/sports/knicks-reunite-with-marcus-morris-sr-on-exhibit-9-deal/',
  },
  {
    NewsID: 98539,
    Source: 'RotoBaller',
    Updated: '2024-09-16T03:18:02',
    TimeAgo: '18 days ago',
    Title: 'Jalen Green Focused On Winning',
    Content:
      'Houston Rockets guard Jalen Green is eligible for a contract extension. While there hasn\'t been an update regarding a potential deal, the 22-year-old doesn\'t seem too concerned. "My main focus is the season ahead of me with the players that we have," said Green in an interview. "Thats the main focus right now, and everything will work itself out." The 22-year-old has had his share of struggles since entering the league in 2021. However, he has still been productive for fantasy managers, most recently finishing the 2023-24 campaign by averaging 19.6 points, 5.2 rebounds, and 3.5 assists. Without question, he has All-Star potential, and his durability is a bonus for fantasy managers despite his underwhelming accuracy from behind the arc. Green and the Rockets have until October 21 to come to terms on a new deal. If that doesn\'t happen, the 2021 No. 2 overall pick will be a restricted free agent next offseason.',
    Url: 'https://www.rotoballer.com/player-news/jalen-green-focused-on-winning/1445477',
    TermsOfUse:
      "RotoBaller Premium News feeds are provided for commercial use and in accordance to the terms set forth within your SportsDataIO's commercial agreement. Please contact sales@sportsdata.io with any questions.",
    Author: 'Staff',
    Categories: 'Lineup, Top-Headlines',
    PlayerID: 20002668,
    TeamID: 22,
    Team: 'HOU',
    PlayerID2: null,
    TeamID2: null,
    Team2: null,
    OriginalSource: 'Jonathan Feigen',
    OriginalSourceUrl:
      'https://www.houstonchronicle.com/sports/rockets/article/houston-jalen-green-contract-extension-19765015.php?utm_campaign=CMSSharingTools(Premium)&amp;utm_source=t.co&amp;utm_medium=referral',
  },
  {
    NewsID: 98536,
    Source: 'RotoBaller',
    Updated: '2024-09-14T20:50:02',
    TimeAgo: '19 days ago',
    Title: 'Isaac Okoro, Cavs Agree To A Three-Year Deal',
    Content:
      "According to ESPN's Adrian Wojnarowski, restricted free-agent forward Isaac Okoro agreed to a three-year, $38 million deal to remain with the Cleveland Cavaliers. Both sides have been at a stalemate regarding a new contract for months. However, things finally worked out, meaning the Cavs will retain a capable defender. Okoro has spent his entire four-year career in Cleveland. He's appeared in 279 regular-season contests for the club, averaging 8.5 points and 2.9 rebounds. With that in mind, the Cavs have Donovan Mitchell, Darius Garland, Evan Mobley, and Jarrett Allen doing most of the heavy lifting offensively, so there's little room for anyone else to get involved. As a result, Okoro likely won't see much attention from fantasy managers heading into the 2024-25 campaign. On the other hand, there could be streaming potential at some point during the season.",
    Url: 'https://www.rotoballer.com/player-news/isaac-okoro-cavs-agree-to-a-three-year-deal/1444350',
    TermsOfUse:
      "RotoBaller Premium News feeds are provided for commercial use and in accordance to the terms set forth within your SportsDataIO's commercial agreement. Please contact sales@sportsdata.io with any questions.",
    Author: 'Staff',
    Categories: 'Lineup, Top-Headlines, Transactions',
    PlayerID: 20002530,
    TeamID: 12,
    Team: 'CLE',
    PlayerID2: null,
    TeamID2: null,
    Team2: null,
    OriginalSource: 'Adrian Wojnarowski',
    OriginalSourceUrl: 'https://x.com/wojespn/status/1835033049148313625',
  },
  {
    NewsID: 98530,
    Source: 'RotoBaller',
    Updated: '2024-09-13T02:38:02',
    TimeAgo: '21 days ago',
    Title: 'Jonathan Kuminga Extension Not Imminent',
    Content:
      "According to Anthony Slater of The Athletic, \"significant progress\" in contract talks between the Golden State Warriors and forward Jonathan Kuminga has not been made. The 2021 No. 7 overall pick is entering the final season of his rookie contract. While the Warriors dismissed trade inquiries this offseason from other teams, it doesn't appear both sides are close to securing an extension. Kuminga finished last season by averaging a career-high 16.1 points and 4.8 rebounds. However, with Klay Thompson now in Dallas, the expectations are higher for the 21-year-old. His shooting percentage from deep needs to improve. But Kuminga will be a consistent member of the Warriors' rotation in 2024-25, giving him value in all fantasy setups. Both sides have until October 21 to agree on a new deal. If it isn't finalized by then, Kuminga will be a restricted free agent next summer.",
    Url: 'https://www.rotoballer.com/player-news/jonathan-kuminga-extension-not-imminent/1442740',
    TermsOfUse:
      "RotoBaller Premium News feeds are provided for commercial use and in accordance to the terms set forth within your SportsDataIO's commercial agreement. Please contact sales@sportsdata.io with any questions.",
    Author: 'Staff',
    Categories: 'Lineup, Top-Headlines',
    PlayerID: 20002661,
    TeamID: 26,
    Team: 'GS',
    PlayerID2: null,
    TeamID2: null,
    Team2: null,
    OriginalSource: 'Anthony Slater',
    OriginalSourceUrl:
      'https://www.nytimes.com/athletic/5701710/2024/09/12/jonathan-kuminga-warriors-extension-talks/?redirected=1',
  },
  {
    NewsID: 98526,
    Source: 'RotoBaller',
    Updated: '2024-09-11T00:38:01',
    TimeAgo: '23 days ago',
    Title: 'Robert Williams III "Very Tradable"',
    Content:
      "Portland Trail Blazers center Robert Williams III (knee) is \"very tradable,\" according to ESPN's Brian Windhorst. Portland has Deandre Ayton, who Windhorst implied isn't in high demand, while drafting UConn's Donovan Clingan during the 2024 NBA Draft. As a result, there's not much room for others. With teams around the National Basketball Association strapped for cash, William's $12.4 million price tag for the 2024-25 campaign makes him an ideal candidate to be moved. Without question, the 26-year-old has plenty of talent, averaging 7.3 points, 6.9 rebounds, and 1.7 blocks throughout his career. Unfortunately, his history of bilateral knee surgeries has kept him from reaching his maximum potential. Williams' days as a starter are likely over. However, he has proven to be a reliable fantasy asset, even when coming off the bench.",
    Url: 'https://www.rotoballer.com/player-news/robert-williams-iii-very-tradable/1440872',
    TermsOfUse:
      "RotoBaller Premium News feeds are provided for commercial use and in accordance to the terms set forth within your SportsDataIO's commercial agreement. Please contact sales@sportsdata.io with any questions.",
    Author: 'Staff',
    Categories: 'Lineup, Top-Headlines',
    PlayerID: 20002024,
    TeamID: 19,
    Team: 'POR',
    PlayerID2: null,
    TeamID2: null,
    Team2: null,
    OriginalSource: 'Brian Windhorst',
    OriginalSourceUrl: 'https://youtu.be/KUe_o0KjRnU?list=PLu1neCd4swuakibtwr6887z4D8YH3YUnK',
  },
  {
    NewsID: 98523,
    Source: 'RotoBaller',
    Updated: '2024-09-10T14:21:11',
    TimeAgo: '23 days ago',
    Title: 'Christian Wood Ruled Out For Eight Weeks Following Knee Surgery',
    Content:
      "Los Angeles Lakers forward/center Christian Wood (knee) will be unavailable for at least eight weeks after undergoing surgery on his left knee. Wood missed the last two months of last season with a left knee injury, and unfortunately, he won't be available for the start of the new campaign either. The 28-year-old big man averaged 6.9 points and 5.1 rebounds in 17.4 minutes with the Lakers last term. Wood is capable of putting up good numbers occasionally, but he doesn't see many minutes in Los Angeles, limiting his fantasy appeal.",
    Url: 'https://www.rotoballer.com/player-news/christian-wood-ruled-out-for-eight-weeks-following-knee-surgery/1440396',
    TermsOfUse:
      "RotoBaller Premium News feeds are provided for commercial use and in accordance to the terms set forth within your SportsDataIO's commercial agreement. Please contact sales@sportsdata.io with any questions.",
    Author: 'Staff',
    Categories: 'Injuries, Lineup',
    PlayerID: 20001527,
    TeamID: 27,
    Team: 'LAL',
    PlayerID2: null,
    TeamID2: null,
    Team2: null,
    OriginalSource: 'ESPN',
    OriginalSourceUrl:
      'https://www.espn.com/nba/story/_/id/41196599/lakers-christian-wood-another-procedure-left-knee',
  },
  {
    NewsID: 98518,
    Source: 'RotoBaller',
    Updated: '2024-09-09T12:00:04',
    TimeAgo: '24 days ago',
    Title: 'Tristan Thompson Agrees To New One-Year Deal With Cavaliers',
    Content:
      "Veteran center Tristan Thompson will spend another campaign with the Cleveland Cavaliers. Thompson, who won the NBA championship with the Cavaliers in 2016, returned to Cleveland last offseason, following short stints with five different teams. Per ESPN's Adrian Wojnarowski, Thompson is now extending his stay for another year. The 33-year-old was a double-double machine during his heydays but has taken on more of a mentorship role on the current Cavaliers team. He posted 3.3 points and 3.6 rebounds in 11.2 minutes last season, coming off the bench in 49 games. Thompson served a 25-game suspension in the middle of the campaign for violating the league's anti-drug program.",
    Url: 'https://www.rotoballer.com/player-news/tristan-thompson-agrees-new-one-year-deal-with-cavaliers/1439252',
    TermsOfUse:
      "RotoBaller Premium News feeds are provided for commercial use and in accordance to the terms set forth within your SportsDataIO's commercial agreement. Please contact sales@sportsdata.io with any questions.",
    Author: 'Staff',
    Categories: 'Lineup',
    PlayerID: 20000577,
    TeamID: 12,
    Team: 'CLE',
    PlayerID2: null,
    TeamID2: null,
    Team2: null,
    OriginalSource: 'Adrian Wojnarowski',
    OriginalSourceUrl: 'https://x.com/wojespn/status/1832080149283471473',
  },
  {
    NewsID: 98516,
    Source: 'RotoBaller',
    Updated: '2024-09-07T19:02:01',
    TimeAgo: '26 days ago',
    Title: 'Jamal Murray Agrees To Contract Extension With Denver',
    Content:
      "According to ESPN's Adrian Wojnarowski, Denver Nuggets guard Jamal Murray agreed to a four-year, $208 million contract extension. The talks between Murray and the Nuggets have been a hot topic, considering his health issues over the years. However, the 27-year-old has been instrumental to Denver's success, helping lead the club to an NBA championship in 2023. As far as Murray's statistical contributions, he finished the 2023-24 campaign by averaging career-highs in points (21.2), assists (6.5), and three-point percentage (42.5%). Without question, he has top-25 fantasy potential in any format. But he'll need to remain on the floor, which has been a significant issue for fantasy managers.",
    Url: 'https://www.rotoballer.com/player-news/jamal-murray-agrees-to-contract-extension-with-denver/1437943',
    TermsOfUse:
      "RotoBaller Premium News feeds are provided for commercial use and in accordance to the terms set forth within your SportsDataIO's commercial agreement. Please contact sales@sportsdata.io with any questions.",
    Author: 'Staff',
    Categories: 'Lineup, Top-Headlines, Transactions',
    PlayerID: 20001666,
    TeamID: 20,
    Team: 'DEN',
    PlayerID2: null,
    TeamID2: null,
    Team2: null,
    OriginalSource: 'Adrian Wojnarowski',
    OriginalSourceUrl: 'https://x.com/wojespn/status/1832489850450448513',
  },
  {
    NewsID: 98510,
    Source: 'RotoBaller',
    Updated: '2024-09-05T11:52:02',
    TimeAgo: '28 days ago',
    Title: 'GG Jackson II Ruled Out For At Least Three Months',
    Content:
      "Memphis Grizzlies forward GG Jackson II (foot) will be out for at least three months, per Shams Charania of The Athletic. Jackson II broke the fifth metatarsal in his right foot in training and had a successful surgery on Wednesday. It's a bitter blow for the 19-year-old, who had an impressive debut campaign in 2023-24, earning a spot on the NBA All-Rookie Second Team. Jackson II averaged 14.8 points and 4.1 rebounds in 25.7 minutes. He likely won't play as big of a role this season if the Grizzlies can keep their core healthy, but the team will definitely miss his scoring ability and youthful energy.",
    Url: 'https://www.rotoballer.com/player-news/gg-jackson-ii-ruled-out-for-at-least-three-months/1435882',
    TermsOfUse:
      "RotoBaller Premium News feeds are provided for commercial use and in accordance to the terms set forth within your SportsDataIO's commercial agreement. Please contact sales@sportsdata.io with any questions.",
    Author: 'Staff',
    Categories: 'Injuries, Lineup',
    PlayerID: 20003064,
    TeamID: 21,
    Team: 'MEM',
    PlayerID2: null,
    TeamID2: null,
    Team2: null,
    OriginalSource: 'Shams Charania',
    OriginalSourceUrl: 'https://x.com/ShamsCharania/status/1831406829467062687',
  },
  {
    NewsID: 98508,
    Source: 'RotoBaller',
    Updated: '2024-09-04T02:00:04',
    TimeAgo: 'over 1 month ago',
    Title: 'RJ Barrett Thrilled To Be In Toronto',
    Content:
      "Toronto Raptors forward RJ Barrett is thrilled to play for his hometown club. \"It's just a literal dream come true,\" said Barrett during an interview. \"When I found out I was coming home, I didn't know how to act. I was pinching myself and telling my people, 'We're really here.'\" The 24-year-old spent his entire career with the Knicks before being dealt to Toronto ahead of last season's deadline. While Barrett was limited to 32 games with the Raptors, he averaged a career-high 21.8 points. With that said, the Raptors aren't even close to being a championship-caliber club. Yet, there's reason to believe Barrett could be in store for his best year to date in 2024-25.",
    Url: 'https://www.rotoballer.com/player-news/rj-barrett-thrilled-to-be-in-toronto/1435061',
    TermsOfUse:
      "RotoBaller Premium News feeds are provided for commercial use and in accordance to the terms set forth within your SportsDataIO's commercial agreement. Please contact sales@sportsdata.io with any questions.",
    Author: 'Staff',
    Categories: 'Lineup, Risers, Top-Headlines',
    PlayerID: 20002272,
    TeamID: 10,
    Team: 'TOR',
    PlayerID2: null,
    TeamID2: null,
    Team2: null,
    OriginalSource: 'David Stol',
    OriginalSourceUrl:
      'https://sharpmagazine.com/2024/08/30/rj-barrett-interview-photoshoot-toronto-raptors/',
  },
  {
    NewsID: 98505,
    Source: 'RotoBaller',
    Updated: '2024-09-03T00:31:02',
    TimeAgo: 'over 1 month ago',
    Title: 'Timberwolves Want Rudy Gobert "For A Long Time"',
    Content:
      'Minnesota Timberwolves center Rudy Gobert (finger) is coming off a season where he won another Defensive Player of the Year award. He also was a member of France during the 2024 Summer Olympics, helping the team capture a silver medal. However, Gobert was limited near the end of the Olympics due to a finger injury. But president of basketball operations Tim Connelly said during an interview that the veteran big man is "good." Connelly also was asked about an extension for Gobert, with the executive stating he\'d like to keep him in Minnesota "for a long time." The 32-year-old averaged 14.0 points, 12.9 rebounds, and 2.1 blocks during the 2023-24 campaign. He also missed only six games. While Gobert has been in the National Basketball Association for over a decade, fantasy managers should continue to view him as a routine starter this season, assuming the finger injury doesn\'t keep him off the floor.',
    Url: 'https://www.rotoballer.com/player-news/timberwolves-want-rudy-gobert-for-a-long-time/1434222',
    TermsOfUse:
      "RotoBaller Premium News feeds are provided for commercial use and in accordance to the terms set forth within your SportsDataIO's commercial agreement. Please contact sales@sportsdata.io with any questions.",
    Author: 'Staff',
    Categories: 'Lineup, Top-Headlines',
    PlayerID: 20000840,
    TeamID: 16,
    Team: 'MIN',
    PlayerID2: null,
    TeamID2: null,
    Team2: null,
    OriginalSource: 'Darren Wolfson',
    OriginalSourceUrl:
      'https://kstp.com/minnesota-sports/1-on-1-with-timberwolves-president-of-operations-tim-connelly-at-state-fair/',
  },
  {
    NewsID: 98500,
    Source: 'RotoBaller',
    Updated: '2024-09-02T12:12:01',
    TimeAgo: 'over 1 month ago',
    Title: 'Reed Sheppard Expected To Play "Significant Role" For Rockets',
    Content:
      "Houston Rockets guard Reed Sheppard faces a battle for playing time in his rookie year on a team filled with young talent. However, it is believed that he will have a place in the rotation. \"He'll be on the floor,\" said ESPN's Tim MacMahon about Sheppard on Brian Windhorst & The Hoop Collective Podcast. \"I think he'll play a significant role as a playmaker off the bench.\" After landing in Houston as the third pick of this year's draft, Sheppard had an outstanding Summer League campaign. Now it's up to him to prove that he can also do it when it really matters, and it looks like the Rockets will give the 20-year-old Kentucky product plenty of opportunities to showcase his talent.",
    Url: 'https://www.rotoballer.com/player-news/reed-sheppard-expected-to-play-significant-role-for-rockets/1433685',
    TermsOfUse:
      "RotoBaller Premium News feeds are provided for commercial use and in accordance to the terms set forth within your SportsDataIO's commercial agreement. Please contact sales@sportsdata.io with any questions.",
    Author: 'Staff',
    Categories: 'Lineup',
    PlayerID: 20003191,
    TeamID: 22,
    Team: 'HOU',
    PlayerID2: null,
    TeamID2: null,
    Team2: null,
    OriginalSource: 'Rockets Wire',
    OriginalSourceUrl:
      'https://rocketswire.usatoday.com/story/sports/nba/rockets/2024/08/30/espns-tim-macmahon-expects-significant-role-for-rockets-rookie-reed-sheppard/75016839007/',
  },
  {
    NewsID: 98499,
    Source: 'RotoBaller',
    Updated: '2024-09-01T15:18:02',
    TimeAgo: 'over 1 month ago',
    Title: 'Grayson Allen Committed To Staying Healthy',
    Content:
      'Phoenix Suns guard/forward Grayson Allen is committed to staying healthy this season. While the former Duke Blue Devil logged 75 games during the regular season, he was limited in the playoffs due to injury. As a result, he hopes the time spent this offseason working on his body will allow him to remain on the floor. Allen, who signed a four-year, $70 million extension with the Suns in April, averaged 13.5 points, 3.9 rebounds, and 3.0 assists during the 2023-24 campaign. He also shot a career-high 46.1% from behind the arc. With Tyus Jones now on the roster, Allen may come off the bench. However, the Suns lack depth outside of the starting lineup, so the 28-year-old should continue to get enough minutes to remain relevant for fantasy managers.',
    Url: 'https://www.rotoballer.com/player-news/grayson-allen-committed-to-staying-healthy/1433265',
    TermsOfUse:
      "RotoBaller Premium News feeds are provided for commercial use and in accordance to the terms set forth within your SportsDataIO's commercial agreement. Please contact sales@sportsdata.io with any questions.",
    Author: 'Staff',
    Categories: 'Lineup, Top-Headlines',
    PlayerID: 20001986,
    TeamID: 29,
    Team: 'PHO',
    PlayerID2: null,
    TeamID2: null,
    Team2: null,
    OriginalSource: 'Duane Rankin',
    OriginalSourceUrl:
      'https://www.azcentral.com/story/sports/nba/suns/2024/08/31/suns-grayson-allen-working-on-speed-power-explosion/75028414007/',
  },
];
